/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VorteileRouteImport } from './routes/vorteile'
import { Route as VergleichRouteImport } from './routes/vergleich'
import { Route as UeberDieseWebsiteRouteImport } from './routes/ueber-diese-website'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchienenlosePoolueberdachungenRouteImport } from './routes/schienenlose-poolueberdachungen'
import { Route as RatgeberRouteImport } from './routes/ratgeber'
import { Route as PflegeWartungRouteImport } from './routes/pflege-wartung'
import { Route as ModelleRouteImport } from './routes/modelle'
import { Route as KontaktRouteImport } from './routes/kontakt'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ErsatzteileRouteImport } from './routes/ersatzteile'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'

const VorteileRoute = VorteileRouteImport.update({
  id: '/vorteile',
  path: '/vorteile',
  getParentRoute: () => rootRouteImport,
} as any)
const VergleichRoute = VergleichRouteImport.update({
  id: '/vergleich',
  path: '/vergleich',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberDieseWebsiteRoute = UeberDieseWebsiteRouteImport.update({
  id: '/ueber-diese-website',
  path: '/ueber-diese-website',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchienenlosePoolueberdachungenRoute =
  SchienenlosePoolueberdachungenRouteImport.update({
    id: '/schienenlose-poolueberdachungen',
    path: '/schienenlose-poolueberdachungen',
    getParentRoute: () => rootRouteImport,
  } as any)
const RatgeberRoute = RatgeberRouteImport.update({
  id: '/ratgeber',
  path: '/ratgeber',
  getParentRoute: () => rootRouteImport,
} as any)
const PflegeWartungRoute = PflegeWartungRouteImport.update({
  id: '/pflege-wartung',
  path: '/pflege-wartung',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelleRoute = ModelleRouteImport.update({
  id: '/modelle',
  path: '/modelle',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktRoute = KontaktRouteImport.update({
  id: '/kontakt',
  path: '/kontakt',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ErsatzteileRoute = ErsatzteileRouteImport.update({
  id: '/ersatzteile',
  path: '/ersatzteile',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/modelle': typeof ModelleRoute
  '/pflege-wartung': typeof PflegeWartungRoute
  '/ratgeber': typeof RatgeberRoute
  '/schienenlose-poolueberdachungen': typeof SchienenlosePoolueberdachungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-diese-website': typeof UeberDieseWebsiteRoute
  '/vergleich': typeof VergleichRoute
  '/vorteile': typeof VorteileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/modelle': typeof ModelleRoute
  '/pflege-wartung': typeof PflegeWartungRoute
  '/ratgeber': typeof RatgeberRoute
  '/schienenlose-poolueberdachungen': typeof SchienenlosePoolueberdachungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-diese-website': typeof UeberDieseWebsiteRoute
  '/vergleich': typeof VergleichRoute
  '/vorteile': typeof VorteileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/ersatzteile': typeof ErsatzteileRoute
  '/faq': typeof FaqRoute
  '/impressum': typeof ImpressumRoute
  '/kontakt': typeof KontaktRoute
  '/modelle': typeof ModelleRoute
  '/pflege-wartung': typeof PflegeWartungRoute
  '/ratgeber': typeof RatgeberRoute
  '/schienenlose-poolueberdachungen': typeof SchienenlosePoolueberdachungenRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/ueber-diese-website': typeof UeberDieseWebsiteRoute
  '/vergleich': typeof VergleichRoute
  '/vorteile': typeof VorteileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/ersatzteile'
    | '/faq'
    | '/impressum'
    | '/kontakt'
    | '/modelle'
    | '/pflege-wartung'
    | '/ratgeber'
    | '/schienenlose-poolueberdachungen'
    | '/sitemap.xml'
    | '/ueber-diese-website'
    | '/vergleich'
    | '/vorteile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/ersatzteile'
    | '/faq'
    | '/impressum'
    | '/kontakt'
    | '/modelle'
    | '/pflege-wartung'
    | '/ratgeber'
    | '/schienenlose-poolueberdachungen'
    | '/sitemap.xml'
    | '/ueber-diese-website'
    | '/vergleich'
    | '/vorteile'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/ersatzteile'
    | '/faq'
    | '/impressum'
    | '/kontakt'
    | '/modelle'
    | '/pflege-wartung'
    | '/ratgeber'
    | '/schienenlose-poolueberdachungen'
    | '/sitemap.xml'
    | '/ueber-diese-website'
    | '/vergleich'
    | '/vorteile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ErsatzteileRoute: typeof ErsatzteileRoute
  FaqRoute: typeof FaqRoute
  ImpressumRoute: typeof ImpressumRoute
  KontaktRoute: typeof KontaktRoute
  ModelleRoute: typeof ModelleRoute
  PflegeWartungRoute: typeof PflegeWartungRoute
  RatgeberRoute: typeof RatgeberRoute
  SchienenlosePoolueberdachungenRoute: typeof SchienenlosePoolueberdachungenRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UeberDieseWebsiteRoute: typeof UeberDieseWebsiteRoute
  VergleichRoute: typeof VergleichRoute
  VorteileRoute: typeof VorteileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vorteile': {
      id: '/vorteile'
      path: '/vorteile'
      fullPath: '/vorteile'
      preLoaderRoute: typeof VorteileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vergleich': {
      id: '/vergleich'
      path: '/vergleich'
      fullPath: '/vergleich'
      preLoaderRoute: typeof VergleichRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-diese-website': {
      id: '/ueber-diese-website'
      path: '/ueber-diese-website'
      fullPath: '/ueber-diese-website'
      preLoaderRoute: typeof UeberDieseWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schienenlose-poolueberdachungen': {
      id: '/schienenlose-poolueberdachungen'
      path: '/schienenlose-poolueberdachungen'
      fullPath: '/schienenlose-poolueberdachungen'
      preLoaderRoute: typeof SchienenlosePoolueberdachungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber': {
      id: '/ratgeber'
      path: '/ratgeber'
      fullPath: '/ratgeber'
      preLoaderRoute: typeof RatgeberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pflege-wartung': {
      id: '/pflege-wartung'
      path: '/pflege-wartung'
      fullPath: '/pflege-wartung'
      preLoaderRoute: typeof PflegeWartungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modelle': {
      id: '/modelle'
      path: '/modelle'
      fullPath: '/modelle'
      preLoaderRoute: typeof ModelleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt': {
      id: '/kontakt'
      path: '/kontakt'
      fullPath: '/kontakt'
      preLoaderRoute: typeof KontaktRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ersatzteile': {
      id: '/ersatzteile'
      path: '/ersatzteile'
      fullPath: '/ersatzteile'
      preLoaderRoute: typeof ErsatzteileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ErsatzteileRoute: ErsatzteileRoute,
  FaqRoute: FaqRoute,
  ImpressumRoute: ImpressumRoute,
  KontaktRoute: KontaktRoute,
  ModelleRoute: ModelleRoute,
  PflegeWartungRoute: PflegeWartungRoute,
  RatgeberRoute: RatgeberRoute,
  SchienenlosePoolueberdachungenRoute: SchienenlosePoolueberdachungenRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UeberDieseWebsiteRoute: UeberDieseWebsiteRoute,
  VergleichRoute: VergleichRoute,
  VorteileRoute: VorteileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
